function CodeDefine() { 
this.def = new Array();
this.def["LaneDetection_rt_powd_snf"] = {file: "LaneDetection_c.html",line:132,type:"fcn"};
this.def["LaneDetection_Start"] = {file: "LaneDetection_c.html",line:178,type:"fcn"};
this.def["LaneDetection"] = {file: "LaneDetection_c.html",line:348,type:"fcn"};
this.def["LaneDetection_initialize"] = {file: "LaneDetection_c.html",line:1465,type:"fcn"};
this.def["LaneDetection_RT_MODEL"] = {file: "LaneDetection_h.html",line:38,type:"type"};
this.def["LaneDetectio_emxArray_int32_T_5"] = {file: "LaneDetection_h.html",line:54,type:"type"};
this.def["LaneDetection_b_cell_wrap_0"] = {file: "LaneDetection_h.html",line:71,type:"type"};
this.def["LaneDetection_DW_f"] = {file: "LaneDetection_h.html",line:136,type:"type"};
this.def["LaneDetection_MdlrefDW"] = {file: "LaneDetection_h.html",line:146,type:"type"};
this.def["rtCP_pooled_5yIRIYjLvEep"] = {file: "../../_sharedutils/html/const_params_c.html",line:13,type:"var"};
this.def["rtCP_pooled_9H9mPzIgD49d"] = {file: "../../_sharedutils/html/const_params_c.html",line:17,type:"var"};
this.def["rtCP_pooled_C08a0ezfB1lz"] = {file: "../../_sharedutils/html/const_params_c.html",line:20,type:"var"};
this.def["rtCP_pooled_EasQq0RLXsWg"] = {file: "../../_sharedutils/html/const_params_c.html",line:24,type:"var"};
this.def["rtCP_pooled_I29smDgh1ZlF"] = {file: "../../_sharedutils/html/const_params_c.html",line:37,type:"var"};
this.def["rtCP_pooled_OHe5xkPYJZLy"] = {file: "../../_sharedutils/html/const_params_c.html",line:41,type:"var"};
this.def["rtCP_pooled_P9txNi55UAyH"] = {file: "../../_sharedutils/html/const_params_c.html",line:43,type:"var"};
this.def["rtCP_pooled_RXsOmBvvADoW"] = {file: "../../_sharedutils/html/const_params_c.html",line:49,type:"var"};
this.def["rtCP_pooled_ai66rjwJqI4l"] = {file: "../../_sharedutils/html/const_params_c.html",line:52,type:"var"};
this.def["rtCP_pooled_anbyKQaxvNBm"] = {file: "../../_sharedutils/html/const_params_c.html",line:54,type:"var"};
this.def["rtCP_pooled_berHTRPvDDTn"] = {file: "../../_sharedutils/html/const_params_c.html",line:56,type:"var"};
this.def["rtCP_pooled_eOCOUVt9XfID"] = {file: "../../_sharedutils/html/const_params_c.html",line:59,type:"var"};
this.def["rtCP_pooled_gtKkVs9eS62J"] = {file: "../../_sharedutils/html/const_params_c.html",line:87,type:"var"};
this.def["rtCP_pooled_hNlvttwOChI0"] = {file: "../../_sharedutils/html/const_params_c.html",line:120,type:"var"};
this.def["rtCP_pooled_lpgonDqdKy1l"] = {file: "../../_sharedutils/html/const_params_c.html",line:127,type:"var"};
this.def["rtCP_pooled_m2kEXjm10gu6"] = {file: "../../_sharedutils/html/const_params_c.html",line:136,type:"var"};
this.def["rtCP_pooled_twUID13wkc9R"] = {file: "../../_sharedutils/html/const_params_c.html",line:140,type:"var"};
this.def["rtCP_pooled_vw7bACqMwvtP"] = {file: "../../_sharedutils/html/const_params_c.html",line:144,type:"var"};
this.def["div_nde_s32_floor"] = {file: "../../_sharedutils/html/div_nde_s32_floor_c.html",line:14,type:"fcn"};
this.def["mul_s32_loSR"] = {file: "../../_sharedutils/html/mul_s32_loSR_c.html",line:15,type:"fcn"};
this.def["mul_ssu32_loSR"] = {file: "../../_sharedutils/html/mul_ssu32_loSR_c.html",line:15,type:"fcn"};
this.def["mul_wide_s32"] = {file: "../../_sharedutils/html/mul_wide_s32_c.html",line:14,type:"fcn"};
this.def["mul_wide_su32"] = {file: "../../_sharedutils/html/mul_wide_su32_c.html",line:14,type:"fcn"};
this.def["chunk_T"] = {file: "../../_sharedutils/html/multiword_types_h.html",line:18,type:"type"};
this.def["uchunk_T"] = {file: "../../_sharedutils/html/multiword_types_h.html",line:19,type:"type"};
this.def["rtGetInf"] = {file: "../../_sharedutils/html/rtGetInf_c.html",line:22,type:"fcn"};
this.def["rtGetInfF"] = {file: "../../_sharedutils/html/rtGetInf_c.html",line:46,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "../../_sharedutils/html/rtGetInf_c.html",line:57,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "../../_sharedutils/html/rtGetInf_c.html",line:81,type:"fcn"};
this.def["rtGetNaN"] = {file: "../../_sharedutils/html/rtGetNaN_c.html",line:22,type:"fcn"};
this.def["rtGetNaNF"] = {file: "../../_sharedutils/html/rtGetNaN_c.html",line:46,type:"fcn"};
this.def["rtInf"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:20,type:"var"};
this.def["rtMinusInf"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:21,type:"var"};
this.def["rtNaN"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:22,type:"var"};
this.def["rtInfF"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:23,type:"var"};
this.def["rtMinusInfF"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:24,type:"var"};
this.def["rtNaNF"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:25,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:31,type:"fcn"};
this.def["rtIsInf"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:43,type:"fcn"};
this.def["rtIsInfF"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:49,type:"fcn"};
this.def["rtIsNaN"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:55,type:"fcn"};
this.def["rtIsNaNF"] = {file: "../../_sharedutils/html/rt_nonfinite_c.html",line:61,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "../../_sharedutils/html/rt_nonfinite_h.html",line:32,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "../../_sharedutils/html/rt_nonfinite_h.html",line:39,type:"type"};
this.def["IEEESingle"] = {file: "../../_sharedutils/html/rt_nonfinite_h.html",line:46,type:"type"};
this.def["int8_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:42,type:"type"};
this.def["uint8_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:43,type:"type"};
this.def["int16_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:44,type:"type"};
this.def["uint16_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:45,type:"type"};
this.def["int32_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:46,type:"type"};
this.def["uint32_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:47,type:"type"};
this.def["real32_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:48,type:"type"};
this.def["real64_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:49,type:"type"};
this.def["real_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:55,type:"type"};
this.def["time_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:56,type:"type"};
this.def["boolean_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:57,type:"type"};
this.def["int_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:58,type:"type"};
this.def["uint_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:59,type:"type"};
this.def["ulong_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:60,type:"type"};
this.def["char_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:61,type:"type"};
this.def["uchar_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:62,type:"type"};
this.def["byte_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:63,type:"type"};
this.def["pointer_T"] = {file: "../../_sharedutils/html/rtwtypes_h.html",line:81,type:"type"};
this.def["MWVIP_Hough_D"] = {file: "hough_d_rt_c.html",line:8,type:"fcn"};
this.def["MWVIP_Hough_R"] = {file: "hough_r_rt_c.html",line:8,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["LaneDetection_c.html"] = "../LaneDetection.c";
	this.html2Root["LaneDetection_c.html"] = "LaneDetection_c.html";
	this.html2SrcPath["LaneDetection_h.html"] = "../LaneDetection.h";
	this.html2Root["LaneDetection_h.html"] = "LaneDetection_h.html";
	this.html2SrcPath["const_params_c.html"] = "../const_params.c";
	this.html2Root["const_params_c.html"] = "../../_sharedutils/html/const_params_c.html";
	this.html2SrcPath["div_nde_s32_floor_c.html"] = "../div_nde_s32_floor.c";
	this.html2Root["div_nde_s32_floor_c.html"] = "../../_sharedutils/html/div_nde_s32_floor_c.html";
	this.html2SrcPath["div_nde_s32_floor_h.html"] = "../div_nde_s32_floor.h";
	this.html2Root["div_nde_s32_floor_h.html"] = "../../_sharedutils/html/div_nde_s32_floor_h.html";
	this.html2SrcPath["mul_s32_loSR_c.html"] = "../mul_s32_loSR.c";
	this.html2Root["mul_s32_loSR_c.html"] = "../../_sharedutils/html/mul_s32_loSR_c.html";
	this.html2SrcPath["mul_s32_loSR_h.html"] = "../mul_s32_loSR.h";
	this.html2Root["mul_s32_loSR_h.html"] = "../../_sharedutils/html/mul_s32_loSR_h.html";
	this.html2SrcPath["mul_ssu32_loSR_c.html"] = "../mul_ssu32_loSR.c";
	this.html2Root["mul_ssu32_loSR_c.html"] = "../../_sharedutils/html/mul_ssu32_loSR_c.html";
	this.html2SrcPath["mul_ssu32_loSR_h.html"] = "../mul_ssu32_loSR.h";
	this.html2Root["mul_ssu32_loSR_h.html"] = "../../_sharedutils/html/mul_ssu32_loSR_h.html";
	this.html2SrcPath["mul_wide_s32_c.html"] = "../mul_wide_s32.c";
	this.html2Root["mul_wide_s32_c.html"] = "../../_sharedutils/html/mul_wide_s32_c.html";
	this.html2SrcPath["mul_wide_s32_h.html"] = "../mul_wide_s32.h";
	this.html2Root["mul_wide_s32_h.html"] = "../../_sharedutils/html/mul_wide_s32_h.html";
	this.html2SrcPath["mul_wide_su32_c.html"] = "../mul_wide_su32.c";
	this.html2Root["mul_wide_su32_c.html"] = "../../_sharedutils/html/mul_wide_su32_c.html";
	this.html2SrcPath["mul_wide_su32_h.html"] = "../mul_wide_su32.h";
	this.html2Root["mul_wide_su32_h.html"] = "../../_sharedutils/html/mul_wide_su32_h.html";
	this.html2SrcPath["multiword_types_h.html"] = "../multiword_types.h";
	this.html2Root["multiword_types_h.html"] = "../../_sharedutils/html/multiword_types_h.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "../../_sharedutils/html/rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "../../_sharedutils/html/rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "../../_sharedutils/html/rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "../../_sharedutils/html/rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "../../_sharedutils/html/rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "../../_sharedutils/html/rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "../../_sharedutils/html/rtwtypes_h.html";
	this.html2SrcPath["hough_d_rt_c.html"] = "../../../../../../../../../Program Files/MATLAB/R2017a/toolbox/vision/visionrt/viphough/hough_d_rt.c";
	this.html2Root["hough_d_rt_c.html"] = "hough_d_rt_c.html";
	this.html2SrcPath["hough_r_rt_c.html"] = "../../../../../../../../../Program Files/MATLAB/R2017a/toolbox/vision/visionrt/viphough/hough_r_rt.c";
	this.html2Root["hough_r_rt_c.html"] = "hough_r_rt_c.html";
	this.html2SrcPath["viphough_rt_h.html"] = "../../../../../../../../../Program Files/MATLAB/R2017a/toolbox/vision/visionrt/export/include/visionrt/viphough_rt.h";
	this.html2Root["viphough_rt_h.html"] = "viphough_rt_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"LaneDetection_c.html","LaneDetection_h.html","const_params_c.html","div_nde_s32_floor_c.html","div_nde_s32_floor_h.html","mul_s32_loSR_c.html","mul_s32_loSR_h.html","mul_ssu32_loSR_c.html","mul_ssu32_loSR_h.html","mul_wide_s32_c.html","mul_wide_s32_h.html","mul_wide_su32_c.html","mul_wide_su32_h.html","multiword_types_h.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","hough_d_rt_c.html","hough_r_rt_c.html","viphough_rt_h.html","MW_target_hardware_resources_h.html"];
